import { ArrowRight, ArrowUpRight, Bell, BookOpen, Building2, CalendarDays, CheckCircle2, ChevronRight, GraduationCap, IndianRupee, Menu, ShieldCheck, Sparkles, Star, Trophy, X } from 'lucide-react';
import { useState } from 'react';
import { AuthPage } from './AuthPage';
import { CollegeAdminPortal } from './CollegeAdminPortal';
import { referenceContent } from './referenceContent';
import { StudentPortal } from './StudentPortal';

type View = 'home' | 'student' | 'admin' | 'login' | 'register';
const navItems = ['About Us', 'Courses', 'Branches', 'Results', 'Gallery', 'Contact'];

export function App() {
  const [view, setView] = useState<View>('home');
  const [mobileOpen, setMobileOpen] = useState(false);
  const [studentId, setStudentId] = useState('');
  if (view === 'login' || view === 'register') return <AuthPage mode={view} onModeChange={setView} onBack={() => setView('home')} onAuthenticated={(authenticatedStudentId) => { setStudentId(authenticatedStudentId); setView('student'); }} />;
  if (view === 'student' && studentId) return <StudentPortal studentId={studentId} onBack={() => setView('home')} />;
  if (view === 'admin') return <CollegeAdminPortal onBack={() => setView('home')} />;
  return <main className="site-shell"><header className="topbar"><a className="brand" href="#home"><span className="brand-mark">N</span><span><strong>NSR</strong><small>IMPULSE KNOWLEDGE PARK</small></span></a><button className="menu-button" onClick={() => setMobileOpen(!mobileOpen)} aria-label="Toggle menu">{mobileOpen ? <X size={20} /> : <Menu size={20} />}</button><nav className={mobileOpen ? 'nav open' : 'nav'}>{navItems.map(item => <a key={item} href={`#${item.toLowerCase().replaceAll(' ', '-')}`} onClick={() => setMobileOpen(false)}>{item}</a>)}<button className="nav-login" onClick={() => setView('login')}>Student login <ArrowUpRight size={16} /></button></nav></header>
    <section className="hero reference-hero" id="home"><div className="hero-copy"><p className="eyebrow"><Sparkles size={15} /> WELCOME TO NSR IMPULSE</p><h1>Start your beautiful<br /><em>and bright future.</em></h1><p className="hero-text">Focused preparation, inspiring mentors, and a learning community that helps every student move with purpose.</p><div className="hero-actions"><button className="primary-button" onClick={() => setView('register')}>Join NSR Impulse <ArrowRight size={17} /></button><a className="text-link" href="#about-us">About our approach <ArrowUpRight size={16} /></a></div></div><div className="hero-art"><div className="art-sun"></div><div className="art-card"><span>Admissions open</span><strong>Make room<br />for ambition.</strong><small>JEE · NEET · EAMCET</small></div><div className="art-stamp">NSR<br /><span>learn · lead</span></div></div></section>
    <section className="stats">{referenceContent.stats.map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</section>
    <section className="intro-section" id="about-us"><div className="section-kicker"><span>01</span><p className="eyebrow">OUR PURPOSE</p></div><div><h2>Learning with a<br /><em>longer view.</em></h2><p>NSR Impulse brings together rigorous academic preparation and the human support students need to keep going. Across our campuses, we build habits that last beyond an exam hall.</p><a className="text-link" href="#facilities">Discover our facilities <ArrowUpRight size={16} /></a></div></section>
    <section className="facilities" id="facilities"><div className="section-heading"><div><p className="eyebrow">WHAT WE BELIEVE</p><h2>More than<br /><em>a classroom.</em></h2></div><p>Every detail has a job: make learning clearer, calmer, and more consistent.</p></div><div className="facility-grid">{referenceContent.facilities.map(([title, description], index) => <article key={title} className={index === 1 ? 'featured' : ''}><span className="facility-number">0{index + 1}</span><div className="facility-icon">{index === 0 ? <ShieldCheck /> : index === 1 ? <GraduationCap /> : index === 2 ? <BookOpen /> : <Building2 />}</div><h3>{title}</h3><p>{description}</p><ChevronRight size={17} /></article>)}</div></section>
    <section className="courses-section" id="courses"><div className="section-heading"><div><p className="eyebrow">OUR COURSES</p><h2>Find your<br /><em>next challenge.</em></h2></div><p>Structured pathways for students preparing to take a confident step forward.</p></div><div className="course-tabs">{referenceContent.courses.map((course, index) => <button className={index === 0 ? 'active' : ''} key={course}>{course}</button>)}</div><div className="course-feature"><div><span className="course-number">01 / 04</span><h3>Prepare with<br /><em>precision.</em></h3><p>Study plans, regular assessments, and teaching that stays close to the way you learn.</p><button className="primary-button" onClick={() => setView('register')}>Enquire now <ArrowUpRight size={16} /></button></div><div className="course-visual"><Trophy size={42} /><strong>100+</strong><span>rank holders and rising</span></div></div></section>
    <section className="results-section" id="results"><div><p className="eyebrow">RESULTS THAT MATTER</p><h2>Small wins.<br /><em>Big momentum.</em></h2></div><div className="result-list"><div><strong>98%</strong><span>regular assessment participation</span></div><div><strong>100+</strong><span>rank holders supported</span></div><div><strong>5</strong><span>campus communities</span></div></div></section>
    <section className="branches-section" id="branches"><div className="section-heading"><div><p className="eyebrow">OUR BRANCHES</p><h2>Close to<br /><em>your ambition.</em></h2></div><p>Find a campus, find your people, and give your goals a place to grow.</p></div><div className="branch-grid">{referenceContent.branches.map((branch, index) => <article key={branch}><span>0{index + 1}</span><h3>{branch}</h3><p>NSR Impulse Knowledge Park</p><a href="#contact">Explore campus <ArrowUpRight size={15} /></a></article>)}</div></section>
    <section className="voices" id="gallery"><div className="voice-quote"><p className="eyebrow"><Star size={14} /> STUDENT VOICES</p><h2>“The right<br /><em>place to begin.</em>”</h2><p>From the first lesson to the final result, the best progress feels shared.</p></div><div className="voice-card"><div className="voice-avatar">RK</div><p>“The teachers made every difficult topic feel possible. I learned how to prepare, but also how to trust my preparation.”</p><strong>Riya Kumar</strong><span>Student, Hyderabad campus</span></div></section>
    <section className="contact-section" id="contact"><div><p className="eyebrow">COME SAY HELLO</p><h2>Let’s plan your<br /><em>next step.</em></h2></div><div className="contact-details"><p>Admissions, course guidance, and campus visits are just a conversation away.</p><a href="tel:+919390112235">+91 93901 12235</a><a href="mailto:info@nsrimpulse.com">info@nsrimpulse.com</a><span>Simhapuri Colony, Dundigal,<br />Pragathi Nagar, Hyderabad.</span></div></section>
    <footer><div><div className="brand"><span className="brand-mark">N</span><span><strong>NSR</strong><small>IMPULSE KNOWLEDGE PARK</small></span></div><p>One connected community for ambitious learners.</p></div><div className="footer-links"><div><b>Quick links</b><a href="#about-us">About us</a><a href="#courses">Courses</a><a href="#branches">Branches</a></div><div><b>Student access</b><button onClick={() => setView('login')}>Sign in</button><button onClick={() => setView('register')}>Register</button><button onClick={() => setView('admin')}>College admin</button></div></div><small className="copyright">© 2026 NSR Impulse Knowledge Park. All rights reserved.</small></footer>
  </main>;
}

function StudentDashboard({ onBack }: { onBack: () => void }) { return <main className="dashboard"><header className="dash-top"><button className="brand plain" onClick={onBack}><span className="brand-mark">N</span><span><strong>NSR</strong><small>STUDENT PWA</small></span></button><div className="dash-actions"><button aria-label="Notifications"><Bell size={19} /></button><span className="avatar">AK</span></div></header><div className="dash-content"><div className="dash-heading"><div><p className="eyebrow">GOOD MORNING, ARJUN</p><h1>Your learning, <em>in motion.</em></h1></div><span className="status"><CheckCircle2 size={15} /> Active student</span></div><section className="student-grid"><div className="student-id panel"><div className="panel-label">STUDENT ID <span>Immutable record</span></div><strong>NSR-TS-HYD-2026-000001</strong><p>Arjun Kumar · BCA · Hyderabad Campus</p></div><div className="fee-card panel"><div className="panel-label">OUTSTANDING FEES <IndianRupee size={16} /></div><strong>₹70,000</strong><p>of ₹1,00,000 total payable</p><button className="primary-button">Pay next installment <ArrowUpRight size={16} /></button></div><div className="quick panel"><div className="panel-label">QUICK ACCESS</div><div className="quick-links"><button><BookOpen /> Results</button><button><CalendarDays /> Documents</button><button><Bell /> Notices</button></div></div><div className="next panel"><div className="panel-label">NEXT INSTALLMENT <span>Due 15 Nov 2026</span></div><strong>₹25,000</strong><div className="progress"><span></span></div><small>1 of 4 installments paid</small></div></section></div></main>; }
function AdminDashboard({ onBack }: { onBack: () => void }) { return <main className="dashboard admin-dashboard"><header className="dash-top"><button className="brand plain" onClick={onBack}><span className="brand-mark">N</span><span><strong>NSR</strong><small>COLLEGE ADMIN</small></span></button><span className="admin-user">Hyderabad Campus · Admin</span></header><div className="dash-content"><div className="dash-heading"><div><p className="eyebrow">OPERATIONS OVERVIEW</p><h1>Good morning, <em>Meera.</em></h1></div><button className="primary-button">Add student <ArrowUpRight size={16} /></button></div><div className="metric-grid"><div><span>Total students</span><strong>1,248</strong><small>↑ 8.4% this year</small></div><div><span>Pending fees</span><strong>₹18.4L</strong><small>Across 326 students</small></div><div><span>Today's collection</span><strong>₹2.1L</strong><small>↑ 12.7% vs yesterday</small></div><div><span>New admissions</span><strong>38</strong><small>Last 30 days</small></div></div><section className="admin-table panel"><div className="table-head"><div><p className="eyebrow">RECENT ACTIVITY</p><h2>Admissions & payments</h2></div><button className="text-link">View all <ArrowUpRight size={15} /></button></div><div className="table-row table-label"><span>Student</span><span>Course</span><span>Status</span><span>Amount</span></div>{[['Riya Sharma','B.Com · Hyderabad','New admission','₹40,000'],['Karan Reddy','BCA · Hyderabad','Payment received','₹25,000'],['Sana Khan','MBA · Hyderabad','Fee reminder','₹15,000']].map(row => <div className="table-row" key={row[0]}><span><b>{row[0]}</b><small>{row[1]}</small></span><span className="mobile-hide">{row[1]}</span><span className="tag">{row[2]}</span><strong>{row[3]}</strong></div>)}</section></div></main>; }
